### ISSUE TITLE
Master Password stored in plain text in variables and instance metadata

### ISSUE THREAD

**Issue by Victorpalkin** [terraform-google-modules/terraform-google-sap#30]
The master password for SAP system to be installed in examples is provided as an input variable and stored in ```*.tfvars``` file.
Does not look secure even assuming that password value will be removed from repository after installation (could still be found in git history)

The proposal is to generate the random and secure password on the runtime with [random_password resource](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password).
The result can be put into [GCP secrets manager secret](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version)

**Comment by morgante** [comment]
Thanks for bringing this up.

Note that input variable for modules do not necessarily need to come from a tfvars file. They can be injected at runtime (through environment variables), pulled from an external source, or otherwise injected dynamically.

If you'd like to contribute it, it would definitely be good to update one of the [examples](https://github.com/terraform-google-modules/terraform-google-sap/blob/master/examples/sap_hana_ha_simple_example/main.tf) to generate the password using `random_password`.

**Comment by Victorpalkin** [comment]
Even if credentials are injected in runtime - they are still stored in plain text in instance metadata.
It would be better to store in secrets manager, but unfortunately the HANA installation script external to this repository is reading it from metadata.
Can you advice?

In the meanwhile, I will make a pull request with updated examples

**Comment by morgante** [comment]
Yeah unfortunately the best we can do here is to update the examples. We don't manage the install script.

**Comment by sjswerdlow** [comment]
As of V1 users can use a GCP Secret Manager 'secret' (https://cloud.google.com/secret-manager) to securely deploy.
